FROM golang:1.26-alpine AS builder

COPY . /build

WORKDIR /build


COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o ./workerservice cmd/order_workers/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /build/workerservice /bin/workerservice

RUN printenv > .env
CMD ["/bin/workerservice"]
